### PR TITLE
[JENKINS-65030] Table to div migration

### PR DESCRIPTION
**Pull request by asc3ns10n**
Updated jelly files that were affected by the table to div migration in Jenkins 2.264+

### CODE REVIEW

**Comment by monluk** [comment]
I have built this code (with modified pom.xml) and it fixes the problem with missing parameters. Thanks!

**Comment by samgabriel** [comment]
hi @oleg-nenashev any idea when this might be merged. We are actually waiting on this to migrate our jenkins installation

**Comment by duemir** [comment]
Hello @imod 
Would you be able to merge and release this change to fix the compatibility of Scriptler with the Jenkins 2.277.1 and newer?

**Comment by imod** [comment]
@duemir I'm no longer maintaining this plugin - it is open for adoption, feel free to take over: https://plugins.jenkins.io/scriptler/

**Comment by mtughan** [comment]
This looks great to me after testing it, thank you @asc3ns10n!

**Pull request merged**
